#define USB_EP0_BUFF_SIZE 8
#define USB_MAX_NUM_INT 2
#define USB_MAX_EP_NUMBER 2
#define USB_PING_PONG_MODE USB_PING_PONG__FULL_PING_PONG
#define USB_POLLING
#define USB_PULLUP_OPTION USB_PULLUP_ENABLE
#define USB_TRANSCEIVER_OPTION USB_INTERNAL_TRANSCEIVER
#define USB_SPEED_OPTION USB_FULL_SPEED
#define USB_SUPPORT_DEVICE
#define USB_NUM_STRING_DESCRIPTORS 3
#define USB_ENABLE_ALL_HANDLERS
#define USB_USE_CDC

#define CDC_COMM_INTF_ID     0
#define CDC_COMM_EP          1
#define CDC_COMM_IN_EP_SIZE 10

#define CDC_DATA_INTF_ID      1
#define CDC_DATA_EP           2
#define CDC_DATA_OUT_EP_SIZE  1
#define CDC_DATA_IN_EP_SIZE   1
